name: Moon Cloud CI Template

on: [push]

jobs:
  mooncloud_login:
    runs-on: alpine
    env:
      MOONCLOUD_USERNAME: user
      MOONCLOUD_PASSWORD: pass
      MOONCLOUD_API_LOGIN_ENDPOINT: "https://api.v2.moon-cloud.eu/user/login-token/"
    outputs:
      mooncloud_token: token 
    steps:
      - run: apk add curl jq
      - run: >
          echo "MOONCLOUD_TOKEN=$(curl --header "Content-Type: application/json" 
          --request POST 
          --data "{\"username\":\"${{MOONCLOUD_USERNAME}}\",\"password\":\"${{MOONCLOUD_PASSWORD}}\"}" ${{MOONCLOUD_API_LOGIN_ENDPOINT}} | jq '.token' | tr -d '"' )" >> $GITHUB_OUTPUT
  
  mooncloud_evaluation:
    runs-on: alpine
    env:
      MOONCLOUD_UER_ID: 1
      MOONCLOUD_API_UER_ENDPOINT: "https://api.v2.moon-cloud.eu/evaluation-rules/${{MOONCLOUD_UER_ID}}/start/"
    steps:
      - run: apk add curl
      - run: >
          curl --header "Content-Type: application/json" --header "Authorization: Token ${{ needs.mooncloud_login.outputs.mooncloud_token }}"
          --request PUT ${{MOONCLOUD_API_UER_ENDPOINT}}