name: Moon Cloud Evaluation CI Template

on:
  workflow_call:
    inputs:
      mooncloud_uer_id:
        required: true
        type: number
      mooncloud_wait_result:
        required: false
        type: string
        default: "false"
    secrets:
      mooncloud_token:
        required: true

jobs:
  mooncloud_evaluation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.6' 
      - run: sudo apt-get update && sudo apt-get install -y curl
      - run: pip install requests
      - run: curl "https://raw.githubusercontent.com/SESARLab/Moon-Cloud-CI-Injection/main/mooncloud_utils.py" -O
      - run: chmod u+x mooncloud_utils.py
      - run: >
          if [ "${{inputs.mooncloud_wait_result}}" == "true" ]; then
            ./mooncloud_utils.py start-evaluation --token $(echo -n ${{secrets.mooncloud_token}} | base64 --decode) --uer-id ${{inputs.mooncloud_uer_id}} --wait-result
          else
            ./mooncloud_utils.py start-evaluation --token $(echo -n ${{secrets.mooncloud_token}} | base64 --decode) --uer-id ${{inputs.mooncloud_uer_id}}
          fi