name: Moon Cloud Login CI Template

on:
  workflow_call:
    secrets:
      mooncloud_username:
        required: true
      mooncloud_password:
        required: true
    outputs:
      mooncloud_token:
        value: ${{ jobs.mooncloud_login.outputs.mooncloud_token }}


jobs:
  mooncloud_login:
    runs-on: ubuntu-latest
    outputs:
      mooncloud_token: ${{ steps.mooncloud_login.outputs.mooncloud_token }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.6' 
      - run: sudo apt-get update && sudo apt-get install -y curl
      - run: pip install requests
      - run: curl "https://raw.githubusercontent.com/SESARLab/Moon-Cloud-CI-Injection/main/mooncloud_utils.py" -O
      - run: chmod u+x mooncloud_utils.py
      - id: mooncloud_login
        run: |
             MOONCLOUD_TOKEN=$(./mooncloud_utils.py get-token --username ${{secrets.mooncloud_username}} --password $(echo '${{secrets.mooncloud_password}}' | sed 's/\\$/\\\\$/g'))
             if [ -z "$MOONCLOUD_TOKEN" ]; then exit 1; else echo "MOONCLOUD_TOKEN=$(echo $MOONCLOUD_TOKEN | base64 -w 0 )" >> $GITHUB_OUTPUT; fi
          